CREATE TABLE SURVEY
(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  TITLE VARCHAR (255),
  DESCRIPTION VARCHAR (255),
  CREATION_DATE DATE,
  EXPIRATION_DATE DATE,
  LINK VARCHAR (255)
);

CREATE TABLE QUESTION
(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  DESCRIPTION VARCHAR (255)
);

CREATE TABLE QUESTION_SURVEY
(
  QUESTION_ID INT,
  SURVEY_ID INT,
  CONSTRAINT FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID),
  CONSTRAINT FOREIGN KEY (SURVEY_ID) REFERENCES SURVEY(ID)
);

CREATE TABLE ANSWER
(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  CORRECT TINYINT(1),
  USER_ANSWER VARCHAR (255),
  SCALE INT,
  QUESTION_ID INT,
  CONSTRAINT FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID)
);